import { PrismaClient, GardenPlantCategory, GardenLightLevel, WaterNeeds, SoilType, GardenGrowthRate, Difficulty } from '@prisma/client';

const prisma = new PrismaClient();

const img = (name: string) => `https://placehold.co/400x300/5a7c3a/ffffff?text=${encodeURIComponent(name)}`;

async function main() {
  console.log('Seeding Growlog with expanded verified plant data...');

  await prisma.gardenPlant.createMany({
    data: [
      {
        name: 'Tomato', scientificName: 'Solanum lycopersicum', category: GardenPlantCategory.VEGETABLE,
        careDifficulty: Difficulty.INTERMEDIATE, lightRequirement: GardenLightLevel.FULL_SUN, waterNeeds: WaterNeeds.MODERATE,
        soilType: [SoilType.LOAMY], hardinessZoneMin: 3, hardinessZoneMax: 11, growthRate: GardenGrowthRate.FAST,
        matureHeight: 72, matureSpread: 36, daysToHarvest: 70, spacingInches: 24, germinationDaysMin: 5, germinationDaysMax: 10,
        isEdible: true, isPerennial: false, bloomSeason: 'Summer', nativeRegion: 'South America', imageUrl: img('Tomato'),
        description: 'Warm-season vegetable requiring full sun and consistent watering. Indeterminate varieties need staking.',
        plantingGuide: 'Start seeds indoors 6-8 weeks before last frost, or transplant after soil reaches 60°F. Plant deeply, burying 2/3 of the stem.',
        wateringGuide: 'Water deeply 1-2 times per week. Keep soil consistently moist but not soggy. Avoid wetting foliage.',
        fertilizingGuide: 'Use balanced fertilizer at planting, then switch to low-nitrogen, high-phosphorus fertilizer when fruiting begins.',
        pruningGuide: 'Remove suckers on indeterminate varieties. Remove bottom leaves to improve airflow.',
        pestDiseaseGuide: 'Watch for hornworms, aphids, blight, and blossom end rot. Blossom end rot is usually calcium uptake issue from irregular watering.',
        harvestingGuide: 'Harvest when fully colored and slightly soft. Pick before frost and ripen indoors if needed.',
        overwinteringGuide: 'Tomatoes are annuals in most climates. Save seeds from healthy fruits.',
        generalCareTips: 'Mulch to retain moisture. Provide support/cage. Rotate planting location yearly.',
        companionPlants: ['basil', 'marigold', 'carrot', 'parsley', 'onion'], avoidPlants: ['cabbage', 'broccoli', 'fennel', 'corn'],
        tags: ['warm-season', 'staking', 'companion-planting', 'annual'],
      },
      {
        name: 'Basil', scientificName: 'Ocimum basilicum', category: GardenPlantCategory.HERB,
        careDifficulty: Difficulty.BEGINNER, lightRequirement: GardenLightLevel.FULL_SUN, waterNeeds: WaterNeeds.MODERATE,
        soilType: [SoilType.LOAMY, SoilType.SANDY], hardinessZoneMin: 2, hardinessZoneMax: 11, growthRate: GardenGrowthRate.FAST,
        matureHeight: 24, matureSpread: 12, daysToHarvest: 30, spacingInches: 10, germinationDaysMin: 5, germinationDaysMax: 10,
        isEdible: true, isPerennial: false, bloomSeason: 'Summer', nativeRegion: 'Southeast Asia', imageUrl: img('Basil'),
        description: 'Annual herb with aromatic leaves. Pinch flower buds to encourage leaf production.',
        plantingGuide: 'Start indoors 4-6 weeks before last frost or direct sow after frost. Needs warm soil (>50°F).',
        wateringGuide: 'Keep soil consistently moist. Water when top inch dries. Basil wilts quickly in heat.',
        fertilizingGuide: 'Light feeder. Use balanced liquid fertilizer every 4-6 weeks. Avoid too much nitrogen.',
        pruningGuide: 'Pinch off flower buds to prolong leaf production. Harvest top leaves regularly.',
        pestDiseaseGuide: 'Susceptible to aphids, whiteflies, and downy mildew. Ensure good airflow.',
        harvestingGuide: 'Harvest from the top down, cutting just above a leaf pair. Best before flowering.',
        overwinteringGuide: 'Annual. Can bring small plants indoors in pots before frost.',
        generalCareTips: 'Great companion for tomatoes. Sensitive to cold — wait to plant outdoors until nights are reliably above 50°F.',
        companionPlants: ['tomato', 'pepper', 'oregano', 'parsley'], avoidPlants: ['sage', 'rue'],
        tags: ['annual', 'aromatic', 'companion-planting', 'warm-season'],
      },
      {
        name: 'Lavender', scientificName: 'Lavandula angustifolia', category: GardenPlantCategory.FLOWER,
        careDifficulty: Difficulty.BEGINNER, lightRequirement: GardenLightLevel.FULL_SUN, waterNeeds: WaterNeeds.LOW,
        soilType: [SoilType.SANDY, SoilType.LOAMY], hardinessZoneMin: 5, hardinessZoneMax: 9, growthRate: GardenGrowthRate.MODERATE,
        matureHeight: 36, matureSpread: 36, daysToHarvest: 90, spacingInches: 18, germinationDaysMin: 14, germinationDaysMax: 28,
        isEdible: true, isPerennial: true, bloomSeason: 'Summer', nativeRegion: 'Mediterranean', imageUrl: img('Lavender'),
        description: 'Drought-tolerant perennial with fragrant flowers. Excellent drainage required.',
        plantingGuide: 'Plant in spring in very well-draining soil. Mound soil or plant on slope to prevent root rot.',
        wateringGuide: 'Water deeply but infrequently. Allow soil to dry between waterings. Avoid overhead watering.',
        fertilizingGuide: 'Low feeder. Too much fertilizer reduces fragrance and oil production.',
        pruningGuide: 'Prune after flowering to maintain shape. Never cut into woody old growth.',
        pestDiseaseGuide: 'Generally pest-free. Root rot from wet soil is the main killer.',
        harvestingGuide: 'Cut flower stems just as buds begin to open. Hang upside down to dry.',
        overwinteringGuide: 'Hardy in zones 5-9. In colder zones, mulch lightly with gravel or straw.',
        generalCareTips: 'Needs full sun (6+ hours) and lean, alkaline soil. Do not overwater.',
        companionPlants: ['rose', 'sage', 'thyme', 'rosemary'], avoidPlants: ['mint'],
        tags: ['perennial', 'drought-tolerant', 'fragrant', 'pollinator'],
      },
      {
        name: 'Rosemary', scientificName: 'Salvia rosmarinus', category: GardenPlantCategory.HERB,
        careDifficulty: Difficulty.BEGINNER, lightRequirement: GardenLightLevel.FULL_SUN, waterNeeds: WaterNeeds.LOW,
        soilType: [SoilType.SANDY, SoilType.LOAMY], hardinessZoneMin: 7, hardinessZoneMax: 10, growthRate: GardenGrowthRate.SLOW,
        matureHeight: 48, matureSpread: 48, daysToHarvest: 80, spacingInches: 24, germinationDaysMin: 15, germinationDaysMax: 25,
        isEdible: true, isPerennial: true, bloomSeason: 'Spring', nativeRegion: 'Mediterranean', imageUrl: img('Rosemary'),
        description: 'Woody perennial herb, extremely drought-tolerant once established.',
        plantingGuide: 'Plant in well-draining soil in full sun. Container growing recommended in colder zones.',
        wateringGuide: 'Water young plants regularly until established. Mature plants rarely need watering.',
        fertilizingGuide: 'Very light feeder. Too much fertilizer produces weak growth.',
        pruningGuide: 'Prune regularly to prevent woody growth. Harvest sprigs often.',
        pestDiseaseGuide: 'Repels cabbage moths and carrot flies. Can get powdery mildew in humid shade.',
        harvestingGuide: 'Cut sprigs as needed. Flavor best before flowering.',
        overwinteringGuide: 'Hardy to zone 7. In colder zones, grow in containers and overwinter indoors near bright window.',
        generalCareTips: 'Needs excellent drainage. Bring containers indoors before hard frost in cold climates.',
        companionPlants: ['cabbage', 'broccoli', 'carrot', 'sage'], avoidPlants: ['mint'],
        tags: ['perennial', 'drought-tolerant', 'woody', 'pest-repellent'],
      },
      {
        name: 'Sunflower', scientificName: 'Helianthus annuus', category: GardenPlantCategory.FLOWER,
        careDifficulty: Difficulty.BEGINNER, lightRequirement: GardenLightLevel.FULL_SUN, waterNeeds: WaterNeeds.MODERATE,
        soilType: [SoilType.LOAMY, SoilType.SANDY], hardinessZoneMin: 2, hardinessZoneMax: 11, growthRate: GardenGrowthRate.FAST,
        matureHeight: 120, matureSpread: 36, daysToHarvest: 70, spacingInches: 12, germinationDaysMin: 7, germinationDaysMax: 10,
        isEdible: true, isPerennial: false, bloomSeason: 'Summer to Fall', nativeRegion: 'North America', imageUrl: img('Sunflower'),
        description: 'Fast-growing annual with large flower heads that track the sun.',
        plantingGuide: 'Direct sow after frost, 1 inch deep. Thin dwarf varieties 6 inches apart, tall varieties 12-18 inches.',
        wateringGuide: 'Water deeply at base. Needs more water during bud formation. Drought-tolerant once established.',
        fertilizingGuide: 'Light feeder. Too much nitrogen produces tall weak stems.',
        pruningGuide: 'No pruning needed. Stake tall varieties in windy areas.',
        pestDiseaseGuide: 'Watch for aphids, caterpillars, and squirrels eating seeds.',
        harvestingGuide: 'Harvest seeds when back of flower head turns brown. Birds love them, so cover with netting.',
        overwinteringGuide: 'Annual. Save seeds for next year.',
        generalCareTips: 'Allelopathic — can inhibit nearby plants. Plant away from sensitive crops.',
        companionPlants: ['corn', 'squash', 'lettuce'], avoidPlants: ['potato', 'pole beans'],
        tags: ['annual', 'pollinator', 'edible-seeds', 'tall'],
      },
      {
        name: 'Lettuce', scientificName: 'Lactuca sativa', category: GardenPlantCategory.VEGETABLE,
        careDifficulty: Difficulty.BEGINNER, lightRequirement: GardenLightLevel.PARTIAL_SUN, waterNeeds: WaterNeeds.MODERATE,
        soilType: [SoilType.LOAMY], hardinessZoneMin: 2, hardinessZoneMax: 11, growthRate: GardenGrowthRate.FAST,
        matureHeight: 12, matureSpread: 12, daysToHarvest: 30, spacingInches: 8, germinationDaysMin: 2, germinationDaysMax: 10,
        isEdible: true, isPerennial: false, bloomSeason: 'N/A', nativeRegion: 'Mediterranean', imageUrl: img('Lettuce'),
        description: 'Cool-season crop that bolts in heat. Harvest outer leaves for continuous production.',
        plantingGuide: 'Sow seeds directly in early spring and fall. Plant every 2 weeks for succession harvest.',
        wateringGuide: 'Keep soil consistently moist. Lettuce becomes bitter if allowed to dry out.',
        fertilizingGuide: 'Light feeder. Compost at planting is usually sufficient.',
        pruningGuide: 'Harvest outer leaves, leaving center to continue growing. Or harvest whole head at maturity.',
        pestDiseaseGuide: 'Slugs, aphids, and rabbits are common problems. Use row cover for protection.',
        harvestingGuide: 'Harvest in the morning when leaves are crisp. Cut-and-come-again for continuous harvest.',
        overwinteringGuide: 'Cold-hardy varieties can overwinter with row cover in mild climates.',
        generalCareTips: 'Succession plant every 2 weeks. Provide afternoon shade in summer to delay bolting.',
        companionPlants: ['carrot', 'radish', 'strawberry', 'chives'], avoidPlants: ['broccoli', 'cabbage'],
        tags: ['cool-season', 'succession-planting', 'quick-harvest'],
      },
      {
        name: 'Hosta', scientificName: 'Hosta spp.', category: GardenPlantCategory.FLOWER,
        careDifficulty: Difficulty.BEGINNER, lightRequirement: GardenLightLevel.FULL_SHADE, waterNeeds: WaterNeeds.MODERATE,
        soilType: [SoilType.LOAMY, SoilType.CLAY], hardinessZoneMin: 3, hardinessZoneMax: 9, growthRate: GardenGrowthRate.SLOW,
        matureHeight: 24, matureSpread: 36, spacingInches: 24, germinationDaysMin: 14, germinationDaysMax: 21,
        isEdible: false, isPerennial: true, bloomSeason: 'Summer', nativeRegion: 'East Asia', imageUrl: img('Hosta'),
        description: 'Shade-loving perennial grown primarily for foliage.',
        plantingGuide: 'Plant in spring or fall in rich, moist soil in shade. Dig wide hole, keep crown at soil level.',
        wateringGuide: 'Keep soil consistently moist, especially in dry shade. Water deeply during drought.',
        fertilizingGuide: 'Apply balanced slow-release fertilizer in spring.',
        pruningGuide: 'Remove spent flower stalks. Cut back dead foliage in late fall or early spring.',
        pestDiseaseGuide: 'Slugs and deer are the biggest problems. Use slug bait and deer repellent.',
        harvestingGuide: 'N/A',
        overwinteringGuide: 'Dies back in winter. Hardy in zones 3-9. Divide every 3-5 years.',
        generalCareTips: 'Many cultivars available. Blue hostas need more shade; gold varieties tolerate more sun.',
        companionPlants: ['fern', 'astilbe', 'bleeding heart'], avoidPlants: [],
        tags: ['perennial', 'shade', 'foliage'],
      },
      {
        name: 'Mint', scientificName: 'Mentha spp.', category: GardenPlantCategory.HERB,
        careDifficulty: Difficulty.BEGINNER, lightRequirement: GardenLightLevel.PARTIAL_SHADE, waterNeeds: WaterNeeds.HIGH,
        soilType: [SoilType.LOAMY, SoilType.CLAY], hardinessZoneMin: 3, hardinessZoneMax: 11, growthRate: GardenGrowthRate.FAST,
        matureHeight: 24, matureSpread: 24, daysToHarvest: 20, spacingInches: 18, germinationDaysMin: 10, germinationDaysMax: 15,
        isEdible: true, isPerennial: true, bloomSeason: 'Summer', nativeRegion: 'Europe/Asia', imageUrl: img('Mint'),
        description: 'Aggressive spreader — always plant in containers or contained beds.',
        plantingGuide: 'Plant in containers or bottomless pots sunk in ground to contain roots.',
        wateringGuide: 'Keep soil moist. Mint loves water but needs drainage.',
        fertilizingGuide: 'Light feeder. compost at planting is usually enough.',
        pruningGuide: 'Harvest regularly to prevent flowering. Cut back hard in midsummer to refresh growth.',
        pestDiseaseGuide: 'Generally pest-free. Can get rust in humid conditions.',
        harvestingGuide: 'Pick leaves before flowering for best flavor.',
        overwinteringGuide: 'Hardy perennial. Dies back in winter, regrows in spring.',
        generalCareTips: 'Invasive. Never plant directly in open garden beds unless you want it to take over.',
        companionPlants: ['cabbage', 'broccoli', 'tomato'], avoidPlants: ['chamomile', 'lavender'],
        tags: ['perennial', 'invasive', 'container-only', 'pest-repellent'],
      },
      {
        name: 'Blueberry', scientificName: 'Vaccinium corymbosum', category: GardenPlantCategory.FRUIT,
        careDifficulty: Difficulty.INTERMEDIATE, lightRequirement: GardenLightLevel.FULL_SUN, waterNeeds: WaterNeeds.MODERATE,
        soilType: [SoilType.PEATY, SoilType.SANDY], hardinessZoneMin: 3, hardinessZoneMax: 9, growthRate: GardenGrowthRate.SLOW,
        matureHeight: 72, matureSpread: 60, daysToHarvest: 90, spacingInches: 60, germinationDaysMin: 30, germinationDaysMax: 90,
        isEdible: true, isPerennial: true, bloomSeason: 'Spring', nativeRegion: 'North America', imageUrl: img('Blueberry'),
        description: 'Acid-loving shrub. Plant 2+ varieties for cross-pollination.',
        plantingGuide: 'Plant in acidic soil pH 4.5-5.5. Space 4-6 feet apart. Mulch with pine needles or peat.',
        wateringGuide: 'Keep consistently moist, especially during fruiting. Use rain water if possible.',
        fertilizingGuide: 'Use acid-loving plant fertilizer in early spring. Avoid high-nitrogen fertilizers.',
        pruningGuide: 'Prune in late winter. Remove old canes and thin crowded growth.',
        pestDiseaseGuide: 'Birds eat berries — use netting. Watch for mummy berry disease.',
        harvestingGuide: 'Berries are ripe when fully blue and easily detach. Harvest over 2-3 weeks.',
        overwinteringGuide: 'Hardy shrub. Mulch in fall.',
        generalCareTips: 'Requires cross-pollination for best yields. Test soil pH regularly.',
        companionPlants: ['azalea', 'rhododendron'], avoidPlants: ['tomato', 'pepper'],
        tags: ['perennial', 'acid-loving', 'cross-pollination'],
      },
      {
        name: 'Zucchini', scientificName: 'Cucurbita pepo', category: GardenPlantCategory.VEGETABLE,
        careDifficulty: Difficulty.BEGINNER, lightRequirement: GardenLightLevel.FULL_SUN, waterNeeds: WaterNeeds.MODERATE,
        soilType: [SoilType.LOAMY], hardinessZoneMin: 3, hardinessZoneMax: 11, growthRate: GardenGrowthRate.FAST,
        matureHeight: 36, matureSpread: 48, daysToHarvest: 50, spacingInches: 36, germinationDaysMin: 7, germinationDaysMax: 10,
        isEdible: true, isPerennial: false, bloomSeason: 'Summer', nativeRegion: 'Central America', imageUrl: img('Zucchini'),
        description: 'Prolific summer squash. Harvest young for best flavor.',
        plantingGuide: 'Direct sow after last frost in mounds. Can be started indoors 2-3 weeks early.',
        wateringGuide: 'Water deeply at base. Avoid wetting foliage. Consistent moisture prevents misshapen fruit.',
        fertilizingGuide: 'Mix compost into planting hole. Side-dress with compost mid-season.',
        pruningGuide: 'No pruning needed. Remove damaged leaves.',
        pestDiseaseGuide: 'Squash vine borers, cucumber beetles, and powdery mildew are common.',
        harvestingGuide: 'Pick when 6-8 inches long. Frequent harvesting encourages more production.',
        overwinteringGuide: 'Annual. Plants die with first frost.',
        generalCareTips: 'Hand-pollinate if pollinators are scarce. Watch for squash vine borer damage at base of stems.',
        companionPlants: ['corn', 'beans', 'marigold', 'nasturtium'], avoidPlants: ['potato', 'pumpkin'],
        tags: ['annual', 'prolific', 'warm-season'],
      },
      {
        name: 'Pepper', scientificName: 'Capsicum annuum', category: GardenPlantCategory.VEGETABLE,
        careDifficulty: Difficulty.INTERMEDIATE, lightRequirement: GardenLightLevel.FULL_SUN, waterNeeds: WaterNeeds.MODERATE,
        soilType: [SoilType.LOAMY], hardinessZoneMin: 3, hardinessZoneMax: 11, growthRate: GardenGrowthRate.MODERATE,
        matureHeight: 30, matureSpread: 18, daysToHarvest: 65, spacingInches: 18, germinationDaysMin: 7, germinationDaysMax: 14,
        isEdible: true, isPerennial: false, bloomSeason: 'Summer', nativeRegion: 'Central/South America', imageUrl: img('Pepper'),
        description: 'Warm-season crop needing heat and sun. Many varieties from sweet to hot.',
        plantingGuide: 'Start seeds indoors 8-10 weeks before last frost. Transplant when nights stay above 55°F.',
        wateringGuide: 'Keep evenly moist. Stress from drought causes blossom drop.',
        fertilizingGuide: 'Use balanced fertilizer at planting, then low-nitrogen fertilizer during fruiting.',
        pruningGuide: 'Pinch early flowers to encourage bushiness. Stake if heavy fruit load.',
        pestDiseaseGuide: 'Aphids, spider mites, and blossom end rot. Ensure consistent watering.',
        harvestingGuide: 'Pick sweet peppers at any size. Hot peppers get hotter when left to ripen fully.',
        overwinteringGuide: 'Annual in most climates. Can overwinter potted plants indoors in sunny spot.',
        generalCareTips: 'Black plastic mulch warms soil and speeds growth. Do not plant where tomatoes/potatoes grew last year.',
        companionPlants: ['basil', 'tomato', 'onion', 'carrot'], avoidPlants: ['fennel', 'kohlrabi'],
        tags: ['warm-season', 'heat-loving', 'annual'],
      },
      {
        name: 'Strawberry', scientificName: 'Fragaria × ananassa', category: GardenPlantCategory.FRUIT,
        careDifficulty: Difficulty.BEGINNER, lightRequirement: GardenLightLevel.FULL_SUN, waterNeeds: WaterNeeds.MODERATE,
        soilType: [SoilType.LOAMY, SoilType.SANDY], hardinessZoneMin: 3, hardinessZoneMax: 10, growthRate: GardenGrowthRate.MODERATE,
        matureHeight: 8, matureSpread: 12, daysToHarvest: 60, spacingInches: 12, germinationDaysMin: 14, germinationDaysMax: 21,
        isEdible: true, isPerennial: true, bloomSeason: 'Spring', nativeRegion: 'Hybrid', imageUrl: img('Strawberry'),
        description: 'Sweet perennial fruit. June-bearing, everbearing, and day-neutral varieties available.',
        plantingGuide: 'Set plants so crown is at soil level. Space 12-18 inches in rows. Mulch with straw.',
        wateringGuide: 'Keep consistently moist, especially during fruit development. Drip irrigation ideal.',
        fertilizingGuide: 'Feed with balanced fertilizer at planting and after first harvest.',
        pruningGuide: 'Remove runners to encourage fruiting, or let some root for new plants. Remove old leaves in early spring.',
        pestDiseaseGuide: 'Slugs, birds, and gray mold. Use straw mulch and netting.',
        harvestingGuide: 'Pick when fully red. Harvest every 1-2 days during peak season.',
        overwinteringGuide: 'Mulch heavily after ground freezes. Remove mulch in early spring.',
        generalCareTips: 'Replace plants every 3-4 years as productivity declines. Choose variety suited to your climate.',
        companionPlants: ['lettuce', 'spinach', 'borage'], avoidPlants: ['tomato', 'potato', 'pepper'],
        tags: ['perennial', 'fruit', 'runner'],
      },
      {
        name: 'Cucumber', scientificName: 'Cucumis sativus', category: GardenPlantCategory.VEGETABLE,
        careDifficulty: Difficulty.BEGINNER, lightRequirement: GardenLightLevel.FULL_SUN, waterNeeds: WaterNeeds.HIGH,
        soilType: [SoilType.LOAMY], hardinessZoneMin: 4, hardinessZoneMax: 11, growthRate: GardenGrowthRate.FAST,
        matureHeight: 72, matureSpread: 24, daysToHarvest: 55, spacingInches: 12, germinationDaysMin: 4, germinationDaysMax: 10,
        isEdible: true, isPerennial: false, bloomSeason: 'Summer', nativeRegion: 'India', imageUrl: img('Cucumber'),
        description: 'Vining summer crop. Trellis to save space and produce straight fruit.',
        plantingGuide: 'Direct sow after frost, or start indoors 3 weeks early. Plant in mounds or trellis.',
        wateringGuide: 'Keep soil consistently moist. Inconsistent watering causes bitter fruit.',
        fertilizingGuide: 'Add compost at planting. Side-dress with compost mid-season.',
        pruningGuide: 'Train up trellis. Remove damaged leaves.',
        pestDiseaseGuide: 'Cucumber beetles, powdery mildew, and squash bugs.',
        harvestingGuide: 'Pick when firm and green. Overripe cucumbers turn yellow and seedy.',
        overwinteringGuide: 'Annual. Plants die with frost.',
        generalCareTips: 'Trellising improves airflow and reduces disease. Harvest frequently to extend production.',
        companionPlants: ['beans', 'corn', 'radish', 'nasturtium'], avoidPlants: ['potato', 'aromatic herbs'],
        tags: ['annual', 'warm-season', 'vining'],
      },
      {
        name: 'Coneflower', scientificName: 'Echinacea purpurea', category: GardenPlantCategory.FLOWER,
        careDifficulty: Difficulty.BEGINNER, lightRequirement: GardenLightLevel.FULL_SUN, waterNeeds: WaterNeeds.LOW,
        soilType: [SoilType.LOAMY, SoilType.SANDY, SoilType.CLAY], hardinessZoneMin: 3, hardinessZoneMax: 9, growthRate: GardenGrowthRate.MODERATE,
        matureHeight: 36, matureSpread: 18, spacingInches: 18, germinationDaysMin: 10, germinationDaysMax: 20,
        isEdible: false, isPerennial: true, bloomSeason: 'Summer to Fall', nativeRegion: 'North America', imageUrl: img('Coneflower'),
        description: 'Native perennial with daisy-like flowers. Drought-tolerant and pollinator-friendly.',
        plantingGuide: 'Plant in full sun. Tolerates poor soil. Space 18-24 inches apart.',
        wateringGuide: 'Water until established. Very drought-tolerant once mature.',
        fertilizingGuide: 'Minimal fertilization needed. Too much fertilizer causes floppy growth.',
        pruningGuide: 'Deadhead to prolong blooming. Leave seed heads for birds in winter.',
        pestDiseaseGuide: 'Generally pest-free. Aster yellows disease is spread by leafhoppers.',
        harvestingGuide: 'Cut flowers for bouquets. Seed heads attract goldfinches.',
        overwinteringGuide: 'Hardy perennial. Leave stems for winter interest and bird food.',
        generalCareTips: 'Divide clumps every 3-4 years. Deer and rabbit resistant once established.',
        companionPlants: ['black-eyed susan', 'bee balm', 'switchgrass'], avoidPlants: [],
        tags: ['perennial', 'native', 'drought-tolerant', 'pollinator'],
      },
    ],
  });

  console.log('Seed complete!');
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
