import { PrismaClient, GardenPlantCategory, GardenLightLevel, WaterNeeds, SoilType, GardenGrowthRate, Difficulty } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('Seeding Growlog database with verified plant data...');

  const plants = await Promise.all([
    prisma.gardenPlant.create({
      data: {
        name: 'Tomato',
        scientificName: 'Solanum lycopersicum',
        category: GardenPlantCategory.VEGETABLE,
        careDifficulty: Difficulty.INTERMEDIATE,
        lightRequirement: GardenLightLevel.FULL_SUN,
        waterNeeds: WaterNeeds.MODERATE,
        soilType: [SoilType.LOAMY],
        hardinessZoneMin: 3,
        hardinessZoneMax: 11,
        growthRate: GardenGrowthRate.FAST,
        matureHeight: 72,
        matureSpread: 36,
        daysToHarvest: 70,
        isEdible: true,
        isPerennial: false,
        description: 'Warm-season vegetable requiring full sun and consistent watering. Indeterminate varieties need staking. Susceptible to blight, hornworms, and blossom end rot. Companion plant with basil, marigolds, and carrots. Avoid planting near brassicas and fennel.',
        companionPlants: ['basil', 'marigold', 'carrot', 'parsley', 'onion'],
        avoidPlants: ['cabbage', 'broccoli', 'fennel', 'corn'],
        tags: ['vegetable', 'warm-season', 'staking', 'companion-planting'],
      },
    }),
    prisma.gardenPlant.create({
      data: {
        name: 'Basil',
        scientificName: 'Ocimum basilicum',
        category: GardenPlantCategory.HERB,
        careDifficulty: Difficulty.BEGINNER,
        lightRequirement: GardenLightLevel.FULL_SUN,
        waterNeeds: WaterNeeds.MODERATE,
        soilType: [SoilType.LOAMY, SoilType.SANDY],
        hardinessZoneMin: 2,
        hardinessZoneMax: 11,
        growthRate: GardenGrowthRate.FAST,
        matureHeight: 24,
        matureSpread: 12,
        daysToHarvest: 30,
        isEdible: true,
        isPerennial: false,
        description: 'Annual herb with aromatic leaves. Pinch flower buds to encourage leaf production. Excellent companion for tomatoes (improves flavor and repels pests). Sensitive to frost. Harvest regularly to promote bushy growth.',
        companionPlants: ['tomato', 'pepper', 'oregano', 'parsley'],
        avoidPlants: ['sage', 'rue', 'thyme'],
        tags: ['herb', 'annual', 'companion-planting', 'aromatic'],
      },
    }),
    prisma.gardenPlant.create({
      data: {
        name: 'Lavender',
        scientificName: 'Lavandula angustifolia',
        category: GardenPlantCategory.FLOWER,
        careDifficulty: Difficulty.BEGINNER,
        lightRequirement: GardenLightLevel.FULL_SUN,
        waterNeeds: WaterNeeds.LOW,
        soilType: [SoilType.SANDY, SoilType.LOAMY],
        hardinessZoneMin: 5,
        hardinessZoneMax: 9,
        growthRate: GardenGrowthRate.MODERATE,
        matureHeight: 36,
        matureSpread: 36,
        daysToHarvest: 90,
        isEdible: true,
        isPerennial: true,
        bloomSeason: 'Summer',
        description: 'Drought-tolerant perennial with fragrant flowers. Requires excellent drainage and full sun. Prune after flowering to maintain shape. Attracts pollinators and repels deer. Harvest flowers for drying when buds just begin to open.',
        companionPlants: ['rose', 'sage', 'thyme', 'rosemary'],
        avoidPlants: ['mint', 'camellia'],
        tags: ['perennial', 'drought-tolerant', 'pollinator', 'fragrant', 'deer-resistant'],
      },
    }),
    prisma.gardenPlant.create({
      data: {
        name: 'Rosemary',
        scientificName: 'Salvia rosmarinus',
        category: GardenPlantCategory.HERB,
        careDifficulty: Difficulty.BEGINNER,
        lightRequirement: GardenLightLevel.FULL_SUN,
        waterNeeds: WaterNeeds.LOW,
        soilType: [SoilType.SANDY, SoilType.LOAMY],
        hardinessZoneMin: 7,
        hardinessZoneMax: 10,
        growthRate: GardenGrowthRate.SLOW,
        matureHeight: 48,
        matureSpread: 48,
        daysToHarvest: 80,
        isEdible: true,
        isPerennial: true,
        description: 'Woody perennial herb with needle-like leaves. Extremely drought-tolerant once established. Requires excellent drainage. Prune regularly to prevent woody growth. Repels cabbage moths and carrot flies. Can be brought indoors in cold climates.',
        companionPlants: ['cabbage', 'broccoli', 'carrot', 'sage', 'thyme'],
        avoidPlants: ['mint', 'basil'],
        tags: ['perennial', 'drought-tolerant', 'woody', 'deer-resistant', 'pest-repellent'],
      },
    }),
    prisma.gardenPlant.create({
      data: {
        name: 'Sunflower',
        scientificName: 'Helianthus annuus',
        category: GardenPlantCategory.FLOWER,
        careDifficulty: Difficulty.BEGINNER,
        lightRequirement: GardenLightLevel.FULL_SUN,
        waterNeeds: WaterNeeds.MODERATE,
        soilType: [SoilType.LOAMY, SoilType.SANDY],
        hardinessZoneMin: 2,
        hardinessZoneMax: 11,
        growthRate: GardenGrowthRate.FAST,
        matureHeight: 120,
        matureSpread: 36,
        daysToHarvest: 70,
        isEdible: true,
        isPerennial: false,
        bloomSeason: 'Summer to Fall',
        description: 'Fast-growing annual with large flower heads that track the sun. Dwarf varieties available for containers. Seeds are edible and attract birds. May inhibit growth of nearby plants (allelopathic). Stake tall varieties in windy locations.',
        companionPlants: ['corn', 'squash', 'lettuce'],
        avoidPlants: ['potato', 'pole beans'],
        tags: ['annual', 'pollinator', 'edible-seeds', 'tall', 'allelopathic'],
      },
    }),
    prisma.gardenPlant.create({
      data: {
        name: 'Lettuce',
        scientificName: 'Lactuca sativa',
        category: GardenPlantCategory.VEGETABLE,
        careDifficulty: Difficulty.BEGINNER,
        lightRequirement: GardenLightLevel.PARTIAL_SUN,
        waterNeeds: WaterNeeds.MODERATE,
        soilType: [SoilType.LOAMY],
        hardinessZoneMin: 2,
        hardinessZoneMax: 11,
        growthRate: GardenGrowthRate.FAST,
        matureHeight: 12,
        matureSpread: 12,
        daysToHarvest: 30,
        isEdible: true,
        isPerennial: false,
        description: 'Cool-season crop that bolts in heat. Plant in spring and fall. Harvest outer leaves for continuous production. Tolerates partial shade. Succession plant every 2 weeks for continuous harvest. Protect from slugs and aphids.',
        companionPlants: ['carrot', 'radish', 'strawberry', 'chives'],
        avoidPlants: ['broccoli', 'cabbage'],
        tags: ['cool-season', 'succession-planting', 'partial-shade', 'quick-harvest'],
      },
    }),
    prisma.gardenPlant.create({
      data: {
        name: 'Hosta',
        scientificName: 'Hosta spp.',
        category: GardenPlantCategory.FLOWER,
        careDifficulty: Difficulty.BEGINNER,
        lightRequirement: GardenLightLevel.FULL_SHADE,
        waterNeeds: WaterNeeds.MODERATE,
        soilType: [SoilType.LOAMY, SoilType.CLAY],
        hardinessZoneMin: 3,
        hardinessZoneMax: 9,
        growthRate: GardenGrowthRate.SLOW,
        matureHeight: 24,
        matureSpread: 36,
        daysToHarvest: 0,
        isEdible: false,
        isPerennial: true,
        bloomSeason: 'Summer',
        description: 'Shade-loving perennial grown primarily for foliage. Dies back in winter. Susceptible to slugs and deer. Divide every 3-5 years. Excellent for woodland gardens and shaded borders. Hundreds of cultivars available in various sizes and colors.',
        companionPlants: ['fern', 'astilbe', 'bleeding heart', 'coral bells'],
        avoidPlants: [],
        tags: ['perennial', 'shade', 'foliage', 'deer-susceptible', 'slug-susceptible'],
      },
    }),
    prisma.gardenPlant.create({
      data: {
        name: 'Mint',
        scientificName: 'Mentha spp.',
        category: GardenPlantCategory.HERB,
        careDifficulty: Difficulty.BEGINNER,
        lightRequirement: GardenLightLevel.PARTIAL_SHADE,
        waterNeeds: WaterNeeds.HIGH,
        soilType: [SoilType.LOAMY, SoilType.CLAY],
        hardinessZoneMin: 3,
        hardinessZoneMax: 11,
        growthRate: GardenGrowthRate.FAST,
        matureHeight: 24,
        matureSpread: 24,
        daysToHarvest: 20,
        isEdible: true,
        isPerennial: true,
        description: 'Aggressive spreader - always plant in containers or contained beds. Harvest regularly to prevent flowering. Repels ants, cabbage moths, and aphids. Invasive if not controlled. Many varieties available (peppermint, spearmint, chocolate mint).',
        companionPlants: ['cabbage', 'broccoli', 'tomato'],
        avoidPlants: ['chamomile', 'rosemary', 'lavender'],
        tags: ['perennial', 'invasive', 'container-only', 'pest-repellent', 'spreader'],
      },
    }),
    prisma.gardenPlant.create({
      data: {
        name: 'Blueberry',
        scientificName: 'Vaccinium corymbosum',
        category: GardenPlantCategory.FRUIT,
        careDifficulty: Difficulty.INTERMEDIATE,
        lightRequirement: GardenLightLevel.FULL_SUN,
        waterNeeds: WaterNeeds.MODERATE,
        soilType: [SoilType.PEATY, SoilType.SANDY],
        hardinessZoneMin: 3,
        hardinessZoneMax: 9,
        growthRate: GardenGrowthRate.SLOW,
        matureHeight: 72,
        matureSpread: 60,
        daysToHarvest: 90,
        isEdible: true,
        isPerennial: true,
        bloomSeason: 'Spring',
        description: 'Acid-loving shrub requiring pH 4.5-5.5. Plant 2+ varieties for cross-pollination. Requires consistent moisture and acidic soil. Protect from birds with netting. Prune in late winter. Takes 2-3 years to reach full production.',
        companionPlants: ['azalea', 'rhododendron', 'cranberry'],
        avoidPlants: ['tomato', 'pepper', 'eggplant'],
        tags: ['perennial', 'acid-loving', 'cross-pollination', 'netting-required'],
      },
    }),
    prisma.gardenPlant.create({
      data: {
        name: 'Zucchini',
        scientificName: 'Cucurbita pepo',
        category: GardenPlantCategory.VEGETABLE,
        careDifficulty: Difficulty.BEGINNER,
        lightRequirement: GardenLightLevel.FULL_SUN,
        waterNeeds: WaterNeeds.MODERATE,
        soilType: [SoilType.LOAMY],
        hardinessZoneMin: 3,
        hardinessZoneMax: 11,
        growthRate: GardenGrowthRate.FAST,
        matureHeight: 36,
        matureSpread: 48,
        daysToHarvest: 50,
        isEdible: true,
        isPerennial: false,
        description: 'Prolific summer squash. Harvest when 6-8" long for best flavor. Requires pollination (hand-pollinate if fruit drops). Susceptible to powdery mildew and squash vine borers. Plant after last frost. Space plants 3-4 feet apart.',
        companionPlants: ['corn', 'beans', 'nasturtium', 'marigold'],
        avoidPlants: ['potato', 'pumpkin'],
        tags: ['annual', 'prolific', 'warm-season', 'pollination-required'],
      },
    }),
  ]);

  console.log('Seed complete!');
  console.log(`  Garden plants: ${plants.length}`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
